### ISSUE TITLE
Confusing / wrong error message

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/winden#103]
When sending from Winden, if the receiver says "n" in the Python CLI then sending user is presented a confusing error message:
"Connection time out: it looks like the connection between you and the sender was briefly lost".

In fact, the receiving side will have sent an `{"error": ...}` message back with "transfer rejected" or similar as the error message, so we should be able to tell the user here that (instead of the wrong "connection lost" message).

**Comment by meejah** [comment]
It won't let me attach the screenshot, but doesn't say why. I tried both PNG and JPEG.

**Comment by donpui** [comment]
Adding a screenshot:
![Screenshot 2022-12-09 at 15 07 20](https://user-images.githubusercontent.com/104410044/206709316-2265018c-260e-49c4-8c0e-14d37e302865.png)

We receive a message and then even close mailbox with mood error.

We get this messages, as it is default error messages, when we don't match to anything else:
https://github.com/LeastAuthority/winden/blob/7eeba68acedafb5e4180aaa51f34de8c876f0406/client/src/app/util/errors.tsx#L31

However as we receive error: `Error details:  SendErr: TransferError: transfer rejected
`, we should be able to map this error to more proper message.

**Comment by JustusFT** [comment]
Fixed by https://github.com/LeastAuthority/winden/pull/104 and https://github.com/LeastAuthority/winden/pull/114
