### ISSUE TITLE
Sender on Winden doesn't know if Receiver entered code or not till file offer is accepted

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/winden#107]
Currently Sender on Winden.app is not aware if Receiver entered already a code or not.

It would be nice to notify Sender as soon, as Receiver consumes the code correctly.

One of option could be hide part "2. Give the receiver the link below" 
![image](https://user-images.githubusercontent.com/104410044/207039003-de97a2ec-b943-4dbc-b5ab-0cee151ace26.png)
and show something like:

"Code was consumed, please wait till Receiver accept the file" additionally we could add some graphical element.

**Comment by JustusFT** [comment]
Fixed by https://github.com/LeastAuthority/winden/pull/150
