### ISSUE TITLE
Receiver doesn't get any message, when Sender cancels during transfer

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/winden#131]
Receiver doesn't get any message, when Sender cancels during transfer. 
Receiver side just reloads the page.

Maybe after changes related with PR https://github.com/LeastAuthority/winden/pull/114, it is possible better handle this case and display the same message. It will be the same "Transfer cancelled/interrupted" message.

Scenarios:
1. Add bigger file (100mb), share the link
2. Open link on receiver side, start downloading
3. Open Sender side, cancel transfer
4. Receiver page will reload.

**Comment by JustusFT** [comment]
This was fixed since https://github.com/LeastAuthority/winden/pull/136 IIRC
