### ISSUE TITLE
Sentry.io API key change or remove

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/winden#140]
I have removed my Sentry.io developer account (as i could share or transfer it).  Currently used API key will be invalid. This can lead on additional JS errors in development/test environment for Winden.

Possible options:
- remove sentry.io integration at all
- open another free account on Sentry.io and experiment more till final decision made.

There is additional task in IT-OPS for discussion: https://github.com/LeastAuthority/it-ops/issues/64

**Comment by JustusFT** [comment]
Removed by https://github.com/LeastAuthority/winden/pull/142
