### ISSUE TITLE
Improve default image and summary when sharing URL to social media

### ISSUE THREAD

**Issue by AaronH8613b** [LeastAuthority/winden#155]
When sharing the Winden URL within a social media post (ie Twitter), the default image is blank and the summary is too long for the space provided.

I suggest the Winden logo as the default image and reducing the length of the description.

**Comment by meejah** [comment]
From a quick look, there does appear to be some plausible-looking meta tags, so I'm not sure what exactly needs to be changed here. 

```    <meta
      name="twitter:title"
      content="Winden - secure, fast and easy file transfer"
    />
    <meta
      name="twitter:description"
      content="Winden is the private, secure way to send large files at speed. No sign-ups. No snooping. No nonsense."
    />
    <meta name="twitter:image" content="/Winden_landscape_logo.png" />
    <meta name="twitter:site" content="@LeastAuthority" />
    <meta name="twitter:card" content="summary_large_image" />
```

(I'm trying to post a screenshot but it doesn't like it, and won't say why...)

**Comment by meejah** [comment]
![winden-tweeters-smol](https://user-images.githubusercontent.com/145599/226682008-6f9855bd-5dcc-49cc-9237-057407f524c5.jpeg)

**Comment by wuan** [comment]
It seems that only the image is missing here. According to https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image there is a description for the `twitter:image` metadata entry:

> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

On our side we serve the image from https://winden.app/Winden_landscape_logo.png. The PNG image has a size of 800x450 pixels (close to 2:1 aspect ration) with 31 kB. That seems to be well inside the specs.

I guess that we need to make the `content` become a real URL instead of the absolute path we have right now.

**Comment by vu3rdd** [comment]
Looks like `twitter:image` has to be an absolute url? It is not clearly mentioned in the above link, but this is what is there in the leastauthority.com page:
```
<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:image" content="https://leastauthority.com/wp-content/uploads/2020/03/LeastAuthority_Logo_RGB_Horizontal.png" />
	<meta name="twitter:site" content="@LeastAuthority" />
	<meta name="twitter:label1" content="Est. reading time" />
	<meta name="twitter:data1" content="4 minutes" />
```

**Comment by meejah** [comment]
I'm not sure if everything renders the same as it does in my browser, but also the words overflow too -- making them shorter might help its readability? There's no tooltip that I can make appear, so as it is there's two incomplete sentences.

**Comment by vu3rdd** [comment]
According to this page: https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#crawling it indexes the meta information for 7 days.

**Comment by vu3rdd** [comment]
Also some techniques are mentioned here: https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/troubleshooting-cards

I tried url shortners, that didn't fix it. I guess we should try the technique mentioned under "My Card information now refreshes, but images are not updating. How do I get the images to refresh?".

**Comment by wuan** [comment]
Ah thanks, so we also might need to have a look at our `robots.txt` to enable crawler access for the particular files.

**Comment by wuan** [comment]
At least the [Twitter Card Validator](https://cards-dev.twitter.com/validator) mentioned in the reference from @vu3rdd above has no problems with our configuration:
```
INFO:  Page fetched successfully
INFO:  10 metatags were found
INFO:  twitter:card = summary_large_image tag found
INFO:  Card loaded successfully
```

**Comment by AaronH8613b** [comment]
In the full size example (meaning the user opens the Tweet), the current text fits.  
![Screenshot 2023-03-24 173607](https://user-images.githubusercontent.com/86980608/227646134-a2be5f8c-b75a-40fa-aae5-66703047df2a.png)

**Comment by wuan** [comment]
After waiting for the caching to go away we now also have the image included:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/563314/228853979-af04ca07-08b5-4c70-a073-c0dc70f11420.png">

This means that we need to fix the url in the site metadata.

**Comment by wuan** [comment]
But we might need to offer a smaller square image as well, now the layout has changed:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/563314/228855055-6a7340a9-a372-4276-8cc6-1e71e9b6333e.png">
