### ISSUE TITLE
Is it possible to increase file size limit?

### ISSUE THREAD

**Issue by HuakunShen** [LeastAuthority/winden#164]
There is a 200MB file size limit currently. 
wormhole cli doesn't seem to have a file size limit, I can transfer 20GB file. 
Is it possible to increase the file size limit for the web client?

**Comment by btlogy** [comment]
Thank you for you interest @HuakunShen.

Quoting a someone with more knowledge about this, the limit exists for a good reason:
> because of browser APIs, the receiver needs to hold the entire contents of the file in memory at some point.

The [FAQ](https://winden.app/faq) will be update via #170 to better explain this.
