### ISSUE TITLE
Problem with WASM data served without MIME type

### ISSUE THREAD

**Issue by wuan** [LeastAuthority/winden#26]
When the wasm data is served without a given MIME type the following error can be seen in the browser console:

```
TypeError: WebAssembly: Response has unsupported MIME type '' expected 'application/wasm' 
```

This can be fixed by adding the correct MIME type when serving the file. If this is not possible falling back to `WebAssembly.instantiate(...)` instead of `WebAssembly.instatiateStreaming(...)` should help.

**Comment by donpui** [comment]
Not sure about falling back to WebAssembly.instantiate as it might affect how wasm works on certain browsers.

**Comment by wuan** [comment]
Then we need to open a ticket for OVH to fix this.

**Comment by meejah** [comment]
How is this OVH's problem..?

**Comment by wuan** [comment]
We are using a Webhosting service provided by OVH which means we just copy the static files there and their whatever webserver is serving the files. Having the correct MIME type requires configuration of the Webserver which is in this case managed by OVH.

**Comment by meejah** [comment]
Ahh, I see ... sorry I thought we just had VPSes from them.

**Comment by wuan** [comment]
> Not sure about falling back to WebAssembly.instantiate as it might affect how wasm works on certain browsers.
@donpui , do we have more technical insight on that finding?

**Comment by JustusFT** [comment]
We already fall back to `WebAssembly.instantiate` for browsers that don't support `instantiateStreaming`
https://github.com/LeastAuthority/winden/blob/691a0e4557fcbccd548e5b4dafe8c8e01aa586e2/client/src/worker/index.ts#L153-L160

I can remove the branching for now so all browsers use `instantiate` (at least until the MIME type is added in the backend)

**Comment by donpui** [comment]
> 
There is note:
https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate 

Can't find exact issue or discussion about instantiateStreaming. Anyhow it will require quick retest if we don't have prioblem with Mobile browsers on IOS and Android.

**Comment by wuan** [comment]
> > 
> 
> There is note: https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate
> 
> Can't find exact issue or discussion about instantiateStreaming. Anyhow it will require quick retest if we don't have prioblem with Mobile browsers on IOS and Android.

The main concern raised there is that using `WebAssembly.instantiate(...)` is less efficient. As this only happens when loading the app it will most probably not hurt us.

**Comment by wuan** [comment]
Created a ticket at OVH to fix the problem on the server side: https://ca.ovh.com/manager/#/dedicated/support/tickets/6277237

**Comment by wuan** [comment]
As OVH is using Apache we can fix that behaviour with a `.htaccess` file deployed to the source directory having the following content:
```
AddType application/wasm .wasm
```
