### ISSUE TITLE
Remove AWS deployment scripts

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/winden#66]
Do we remove AWS deployment scripts from code or leave them as it even if we are not using our selves?

https://github.com/LeastAuthority/winden/search?q=aws

Pros for leaving, maybe someone else helps this to run quickly on AWS.

**Comment by meejah** [comment]
we should remove code we're not using

(it could be recovered from history so if it seems _really_ useful, maybe a sentence in the readme about how to find it)

**Comment by donpui** [comment]
Removed and deployed
