### ISSUE TITLE
Added warning/confirmation to tab closure on Send instructions screen

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/winden#80]
Original: https://github.com/LeastAuthority/Transfer/issues/21

**Existing behavior**

1. Sender selects or drops a file to send from the Send / default screen.
2. On the Send instructions screen, they are presented with a code/link to share with the intended recipient.
3. After the intended recipient has successfully opened the link or entered the code, and has accepted the download, the Sender will see the Send instructions screen switch to the Send progress screen, and if uninterrupted, to the Send complete screen.
4. However, if they close the tab or navigate to a different page before reaching the Send complete screen, the file transfer will fail.

We are communicating on the Send instructions screen that the sender needs to keep the tab open. However, this message may not be read or clearly understood.

Based on user testing, people seem to be less familiar with synchronous file transfers and do not commonly expect that they need to keep this tab active for the recipient to be able to download the file.

**New behavior**

To help avoid people closing/navigating away from the Send instructions screen, we want to experiment with adding an "Are you sure?" step to this.

This could take the shape of a dialog along the lines of whether the user is sure they want to discard existing changes--something that can help alert them to the fact that this action will have consequences, and possibly bring closer attention to the copy explaining that the tab needs to be kept open.

If we can customize the copy in this dialog, it could take the form of:

```
Closing this tab will cancel the file transfer.
Are you sure you want to close the tab?
Yes, cancel transfer / No
```

**Risks/tradeoffs**

For users who intentionally close the tab while understanding the consequences, this will add unnecessary friction.

**Other**

Some relevant documentation to consider: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event and https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/.

Moved from #OP247

**Comment by JustusFT** [comment]
Fixed by https://github.com/LeastAuthority/winden/pull/102 so will close this issue. We would probably revisit this once multiple file transfer is available (the user should be able to navigate to other screens without getting a warning so they can make additional transfers)
