### ISSUE TITLE
Enable Dependabot for NPM packages

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/winden#86]
Enable Github Dependabot for NPM packages to scan for security issues with packages.

For discussion, should we configure only production packages scanning or also devDependencies?

**Comment by donpui** [comment]
@btlogy may be you could look at this issue?

**Comment by btlogy** [comment]
I just had a quick look. And my first impressions are:
- Dependabot encompasses 3 different features: [alerts](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-are-dependabot-alerts), security and version [updates](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-are-dependabot-updates). Are we talking only about alerts in this issue @donpui?
- Dependabot features can be enabled only by repository [owners or people with admin access](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#feature-availability), which I don't have (yet) in this repository.
- Dependabot feature do not seems to be configurable via the Terraform module we are using today.

@wuan, can you give us some guidance on how to go further here?

As for the discussion, I'm not sure there is a way to scan on production packages. In a repository I'm testing, it seems like we can only enable or disable the Dependabot Alert feature. Not much to configure there.
This being said, my experience with GitHub features is still a WiP...

**Comment by donpui** [comment]
I was more thinking about security alerts. There are possibility to configure via Github interface, but maybe it is possible to configure via .yml file: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file and then push changes here?

**Comment by donpui** [comment]
Also now, if we run npm audit, it will find some issues, but if we omit=dev packages, currently there is no vulnerabilities (by npm audit). For discussion, should we enable for all packages and have pain or should we focus only for prod packages usage (which are deployed)?
FYI @JustusFT

**Comment by wuan** [comment]
Support for the `security_and_analysis` block seems to be on the way: https://github.com/mineiros-io/terraform-github-repository/pull/143

**Comment by btlogy** [comment]
> Support for the `security_and_analysis` block seems to be on the way: [mineiros-io/terraform-github-repository#143](https://github.com/mineiros-io/terraform-github-repository/pull/143)

Good catch @wuan. My search results were empty there (not always indexed apparently).

**Comment by btlogy** [comment]
> I was more thinking about security alerts. There are possibility to configure via Github interface, but maybe it is possible to configure via .yml file: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file and then push changes here?

This looks like a nice way to tune Dendendabot, but I think it needs to be enabled for the repository first.

**Comment by donpui** [comment]
> With this in mind, and since it is only about alerting: should we not then add a GitHub action to `npm audit` rather than enable Dependabot @donpui?

We can have a mix usage, run in Github Actions and also on Github. Github Dependabot provide some Web interface and also can create PRs. 
Downside of CI, is that if there is not changes, not checks are done. Dependabot runs regularly. Although, maybe CI also can be setup regularly.

**Comment by donpui** [comment]
Lets enable Dependabot first (as it is quickest open), while we explore and make other more common via all repos approach.

**Comment by donpui** [comment]
Actually dependabot is already enabled in this repo, however only [Admin](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#access-requirements-for-security-features) level can see. Plus or not, if security check runs in CI, it could be seen for lower rights users.

**Comment by btlogy** [comment]
Nearly 2 months since mineiros-io/terraform-github-repository#143 and not yet merged...
I can push a `dependabot.yml` file, but I feel like I'll be poking in the dark as long as I'm not an Admin...
I'll test in a sandbox repo...

**Comment by wuan** [comment]
We can enable Dependabot manually for selected repositories so that we do not need to wait for the update.

**Comment by donpui** [comment]
Winden it is already enabled.

**Comment by btlogy** [comment]
For the record: I've tested `dependabot.yml` [elsewhere](https://github.com/la-test/sbx-actions/blob/main/.github/dependabot.yml) and this did not enable the alerting.

**Comment by wuan** [comment]
> For the record: I've tested `dependabot.yml` [elsewhere](https://github.com/la-test/sbx-actions/blob/main/.github/dependabot.yml) and this did not enable the alerting.

Having a look at the "Code security and analysis" section in the repo settings it looks like Dependabot is enabled:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/563314/214951411-2a212a7d-2171-46d7-bcb9-e397d93ae212.png">

**Comment by btlogy** [comment]
Thank you @wuan.

From this screenshot we can confirm Dependabot is enabled, but altering is disabled!
Now, when I've asked earlier:
> Dependabot encompasses 3 different features: [alerts](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-are-dependabot-alerts), security and version [updates](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-are-dependabot-updates). Are we talking only about alerts in this issue @donpui?

@donpui replied:
> I was more thinking about security alerts.

Thus, is this issue really resolved?

**Comment by donpui** [comment]
> Thus, is this issue really resolved?

Alerts are enabled, button shows, that you can disable :) However, they are visible in Security Dashboard, but only who have certain rights. Dependabot also allows to create PR automatically, however, this means public disclosure.

**Comment by btlogy** [comment]
> Alerts are enabled, button shows, that you can disable :)

Oups...
Now I see :-p
I found that way of presenting disable/enable button a bit counter-intuitive, but I'll get used to it, I guess.
Thank you @donpui.
