### ISSUE TITLE
Enable Matomo to collect privacy friendly information about app usage

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/winden#89]
Use Matomo to collect privacy friendly information / events about specifically Winden.app usage, which could help us understand users experience, product usage and help make decisions for future improvements. 

- [ ] how many Users come to Winden.app but not started sending files
       **Note**: Partly covered with web access_log statistics, collect total amount of sessions;
- [ ] how many Users come to Winden.app and initiated send files
       **Note**: Mailbox will show only total connection amount for specific agent, but we don't know if it is sent or recieved
- [ ] how many Users successfully sent files in Winden.app
- [ ] how many Users successfully received files in Winden.app
- [ ] how many Users canceled sending files in Winden.app
- [ ] how many Users failed to receive files in Winden.app
- [ ] What file sizes are sent via Winden.app
        **Note**: Relay statistics cover only general traffic, cannot separate per agency
- [ ] how many Users visited other statics pages: Feedback/ Faq/ Privacy / Terms / For Business
       **Note**: Access_log will not show any internal SPA usage
- [ ] Do users try upload large files, which not yet supported
- [ ] What file types Users are sending via Winden.app
- [x] What regions/ countries Users are coming from
      **Note**: Covered by access_log statistics
- [ ] How devices users are accessing to Winden.app to send files and receive files separately
      **Note**: Covered only general statistics by access_log statistics. We cannot separate from what device to which we are sending.
- [ ] Do users get any errors while using Winden.app and what kind of errors
      **Note**: Access_logs doesn't cover this

**Note**: Initial list to discuss what should be and should not be collected. Some information is already collected in Magic-Wormhole backend, but it is common for any clients, who use it and doesn't allow fully separate Winden information and behaviour.

**Comment by meejah** [comment]
A lot of these do not require Matomo (i.e. we have the statistics already).

I don't love the idea of collecting metrics and although Matomo says "privacy friendly" on the label, it's only really "more private than Google Analytics".

So, can we at least separate the list above into stats we already have versus those that we can _only_ get via client-side javascript profiling?

**Comment by donpui** [comment]
Currently we have three source of data:
- **access_logs**, which covers only data related with GET/POST request and doesn't provide internal insides of our SPA application behavior. We can get total amount of visitors, there geo location country/region, bots/robots data
- **Mailbox db** - only covers if to pairs connected or not, but doesn't say anything about transfer if it was successful or not. Even if mailbox logs today agent, however we cannot group by agent and identify how many connections per specific agent we had
- **Relay db** - only covers connections via relay, but lacks of agent identification and doesn't say anything about transfer success or failure itself, where there interruption, did client click cancel or it was other reasons.

Some questions we can try to answer indirectly and with assumptions, for example if we had 300 successful mailbox connections, we assume there was 300 successful transfers and if there are 100 relays connections, then 200 connection where P2P.

However if we look from Winden.app usage perspective, not much we can answers. 

Another thing, we we move away from WebHosting and we could get rid of access_log at all and have only specific events collections for analytic

**Comment by meejah** [comment]
There are never p2p connections from Winden.

I don't understand what the sentence about "move away from WebHosting" means.

You _can_ correlate relay traffic to specific mailboxes via IP addresses.

"What file types": why does this even matter?

**Comment by meejah** [comment]
None of this says what we hope to learn.

With a handful of users and barely any operational experience, why does it matter who clicked "cancel"? What decision will that drive? What is a high-level question we're trying to answer here that _requires_ the collection of _any_ of these data at all (let alone the ones that can only be done via client-side, invasive tracking like Matomo)?

**Comment by meejah** [comment]
Please file a ticket describing "Why" before we can possibly approach or evaluate any implementation detail such as "Matomo", or server-side statistics, or anything else.
